name: Deploy

on: 
  push:
    branches: [ main ]

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0   
      env:                                        
        FTP_SERVER: ${{ secrets.FTP_SERVER }}     
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }} 
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} 
        LOCAL_DIR: public/                           
        REMOTE_DIR: /arch/      
        ARGS: --delete
